[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "opf-fido"
dynamic = ["version"]
requires-python = ">= 3.8"
description = "Format Identification for Digital Objects (FIDO)."
readme = "README.md"
authors = [
    { name = "Adam Farquhar (BL)" }  # Add email if available
    ]
license = "Apache-2.0"
license-files = ["LICENSE.txt"]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    ]   

dependencies = [
    "olefile >= 0.46, < 1",
    "requests >= 2",
    "defusedxml >= 0.7"
    ]

[project.urls]
Homepage = "https://openpreservation.org/technology/products/fido/"
Repository = "https://github.com/openpreserve/fido"
Issues = "https://github.com/openpreserve/fido/issues"

[project.optional-dependencies]
dev = [
    "pytest-cov",
    "flake8",
    ]
build = [
    "build",
    "twine",
    "ruff",
    ]

[project.scripts]
fido = "fido.fido:main"
fido-prepare = "fido.pronom.prepare:main"
fido-toxml = "fido.toxml:main"
fido-update-signatures = "fido.pronom.update_signatures:run"

[tool.setuptools]
include-package-data = true

[tool.setuptools.dynamic]
version = { attr = "fido.__version__" }

[tool.setuptools.packages.find]
include = ["fido*"]

[tool.setuptools.package-data]
"fido" = ["*.*", "conf/*.*", "pronom/*.*"]

[tool.pytest.ini_options]
addopts = "--maxfail=1 --strict-markers"


[tool.flake8]
exclude = ['.venv']
ignore = ['E231', 'E241', 'E501', 'W503', 'E203']
max-line-length = 120
# count = true

[tool.ruff]
line-length = 120